const { emojis } = require('../constants')

module.exports = [
  {
    name: 'Starter Crate',
    description: 'A crate that will help you start your city',
    id: 'starter crate',
    fileId: 'starterCrate',
    emoji: emojis.starterCrate,
    type: 'Crate',
    url: 'https://i.imgur.com/8UFyotO.png',
    rarity: 'Common',
    marketable: false,
    usable: true,
    craftable: false,
    sellTax: 98,
    buyTax: 98,
    buyPrice: 0,
    sellPrice: 0,
    maxItems: 5,
    minItems: 2,
    maxCoins: 10000,
    minCoins: 4000,
    recipie: [],
    loot: [
      {
        name: 'Plastic',
        id: 'plastic',
        emoji: emojis.plastic,
        max: 10,
        min: 5,
        chance: 25
      }, {
        name: 'Metal',
        id: 'metal',
        emoji: emojis.metal,
        max: 10,
        min: 5,
        chance: 25
      }, {
        name: 'Tools',
        id: 'tools',
        emoji: emojis.tools,
        max: 5,
        min: 1,
        chance: 25
      }, {
        name: 'Bricks',
        id: 'bricks',
        emoji: emojis.bricks,
        max: 10,
        min: 4,
        chance: 25
      }
    ]
  },
  {
    name: 'Clay',
    description: 'Found from scavanging',
    id: 'clay',
    fileId: 'clay',
    emoji: emojis.clay,
    type: 'Sellable',
    url: 'https://i.imgur.com/8UFyotO.png',
    rarity: 'Common',
    marketable: true,
    usable: false,
    craftable: false,
    sellTax: 98,
    buyTax: 98,
    buyPrice: 0,
    sellPrice: 0,
    maxItems: 0,
    minItems: 0,
    maxCoins: 0,
    minCoins: 0,
    recipie: [],
    loot: []
  },
  {
   name: 'Bricks',
   description: 'Used to create more buildings for your city',
   id: 'bricks',
   fileId: 'bricks',
   emoji: emojis.bricks,
   type: 'Craftable',
   url: 'https://i.imgur.com/8UFyotO.png',
   rarity: 'Common',
   marketable: true,
   usable: false,
   craftable: true,
   sellTax: 98,
   buyTax: 98,
   buyPrice: 0,
   sellPrice: 0,
   maxItems: 0,
   minItems: 0,
   maxCoins: 0,
   minCoins: 0,
   recipie: [
    {
      id: 'clay',
      fileId: 'clay',
      emoji: emojis.clay,
      name: 'Clay',
      amount: 4
    }
   ],
   loot: []
  }, {
   name: 'Spare Parts',
   description: 'Old rusty bits of metal, could be helpful',
   id: 'spare parts',
   fileId: 'spareParts',
   emoji: emojis.spareParts,
   type: 'Collectable',
   url: 'https://i.imgur.com/8UFyotO.png',
   rarity: 'Uncommon',
   marketable: true,
   usable: false,
   craftable: true,
   sellTax: 98,
   buyTax: 98,
   buyPrice: 0,
   sellPrice: 0,
   maxItems: 0,
   minItems: 0,
   maxCoins: 0,
   minCoins: 0,
   recipie: [
    {
      id: 'metal',
      fileId: 'metal',
      emoji: emojis.metal,
      name: 'Metal',
      amount: 5
    },
    {
      id: 'plastic',
      fileId: 'plastic',
      emoji: emojis.plastic,
      name: 'Plastic',
      amount: 5
    }
   ],
   loot: []
  }, {
   name: 'Metal',
   description: 'Bit rusty but can still be useful',
   id: 'metal',
   fileId: 'metal',
   emoji: emojis.metal,
   type: 'Collectable',
   url: 'https://i.imgur.com/8UFyotO.png',
   rarity: 'Common',
   marketable: true,
   usable: false,
   craftable: false,
   sellTax: 98,
   buyTax: 98,
   buyPrice: 0,
   sellPrice: 0,
   maxItems: 0,
   minItems: 0,
   maxCoins: 0,
   minCoins: 0,
   recipie: [],
   loot: []
  }, {
    name: 'Plastic',
    description: 'Yep, even alot alot alot and a alot more years later is still existing',
    id: 'plastic',
    fileId: 'plastic',
    emoji: emojis.plastic,
    type: 'Collectable',
    url: 'https://i.imgur.com/8UFyotO.png',
    rarity: 'Common',
    marketable: true,
    usable: false,
    craftable: false,
    sellTax: 98,
    buyTax: 98,
    buyPrice: 0,
    sellPrice: 0,
    maxItems: 0,
    minItems: 0,
    maxCoins: 0,
    minCoins: 0,
    recipie: [],
    loot: []
   }, {
    name: 'Wood',
    description: 'An old log found on the ground. Is that a bug I see...',
    id: 'wood',
    fileId: 'wood',
    emoji: emojis.wood,
    type: 'Collectable',
    url: 'https://i.imgur.com/8UFyotO.png',
    rarity: 'Common',
    marketable: true,
    usable: false,
    craftable: false,
    sellTax: 98,
    buyTax: 98,
    buyPrice: 0,
    sellPrice: 0,
    maxItems: 0,
    minItems: 0,
    maxCoins: 0,
    minCoins: 0,
    recipie: [],
    loot: []
   }, {
    name: 'Tools',
    description: 'Drill, hammer, stuff to build a house with',
    id: 'tools',
    fileId: 'tools',
    emoji: emojis.tools,
    type: 'Collectable',
    url: 'https://i.imgur.com/8UFyotO.png',
    rarity: 'Common',
    marketable: true,
    usable: false,
    craftable: true,
    sellTax: 98,
    buyTax: 98,
    buyPrice: 0,
    sellPrice: 0,
    maxItems: 0,
    minItems: 0,
    maxCoins: 0,
    minCoins: 0,
    recipie: [{
      id: 'metal',
      fileId: 'metal',
      name: 'Metal',
      emoji: emojis.metal,
      amount: 3
    }, {
      id: 'plastic',
      fileId: 'plastic',
      name: 'Plastic',
      emoji: emojis.plastic,
      amount: 3
    }],
    loot: []
   }, {
    name: 'Building Supplies',
    description: 'Used to build buildings',
    id: 'building supplies',
    fileId: 'buildingSupplies',
    emoji: emojis.buildingSupplies,
    type: 'Collectable',
    url: 'https://i.imgur.com/8UFyotO.png',
    rarity: 'Common',
    marketable: true,
    usable: false,
    craftable: true,
    sellTax: 98,
    buyTax: 98,
    buyPrice: 0,
    sellPrice: 0,
    maxItems: 0,
    minItems: 0,
    maxCoins: 0,
    minCoins: 0,
    recipie: [{
      id: 'plastic',
      fileId: 'plastic',
      name: 'Plastic',
      emoji: emojis.plastic,
      amount: 5
    }, {
      id: 'metal',
      fileId: 'metal',
      name: 'Metal',
      emoji: emojis.metal,
      amount: 10
    }, {
      id: 'bricks',
      fileId: 'bricks',
      name: 'Bricks',
      emoji: emojis.bricks,
      amount: 5
    }, {
      id: 'tools',
      fileId: 'tools',
      name: 'Tools',
      emoji: emojis.tools,
      amount: 3
    }],
    loot: []
   }, {
    name: 'Quest Crate',
    description: 'A crate found from doing quests',
    id: 'quest crate',
    fileId: 'questCrate',
    emoji: emojis.questCrate,
    type: 'Crate',
    url: 'https://i.imgur.com/8UFyotO.png',
    rarity: 'Rare',
    marketable: true,
    usable: false,
    craftable: false,
    sellTax: 98,
    buyTax: 98,
    buyPrice: 0,
    sellPrice: 0,
    maxItems: 0,
    minItems: 0,
    maxCoins: 0,
    minCoins: 0,
    recipie: [],
    loot: []
   },
]