module.exports = [{
        name: 'Cheese',
        description: 'It\'s just a block of cheese',
        sellPrice: 500,
        buyPrice: 0,
        tradeValue: 100,
        emoji: '<:Cheese:1005438383570571294>',
        id: 'cheese',
        type: 'Sellable',
        rarity: 'Common',
        url: 'https://imgur.com/aF9VMiv.png',
        usable: false
    },
    {
        name: 'XP Coin',
        description: 'This coin gives you a 50% XP boost for 1 hour',
        sellPrice: 1000000,
        buyPrice: 1500000,
        tradeValue: 23000,
        emoji: '<:XPCoin:1005438386787582084>',
        id: 'xp coin',
        type: 'Power-Up',
        rarity: 'Uncommon',
        url: 'https://imgur.com/OjgbjtL.png',
        usable: true
    },
    {
        name: 'KSchlatt Coin',
        description: 'A Coin of KSchlatt\'s pfp given by the devs',
        sellPrice: 0,
        buyPrice: 0,
        tradeValue: 1000000,
        emoji: '<:kschlatt:1005522229511077921>',
        id: 'kschlatt coin',
        type: 'Collectable',
        rarity: 'Unfound',
        url: 'https://imgur.com/CN190J0.png',
        usable: false
    },
    {
        name: 'Bad Coin',
        description: 'A dev item. If you own this you are legendary',
        sellPrice: 0,
        buyPrice: 0,
        tradeValue: 10000000,
        emoji: '<:ThatBadName:1005583434921545788>',
        id: 'bad coin',
        type: 'Collectable',
        rarity: 'Unfound',
        url: 'https://imgur.com/ktTmVOY.png',
        usable: false
    },
    {
        name: 'Funny dog',
        description: 'A Dog with mayo on its head',
        sellPrice: 3000000,
        buyPrice: 0,
        tradeValue: 5000000,
        emoji: '<:FunnyDog:1006293232780587178>',
        id: 'funny dog',
        type: 'Collectable',
        rarity: 'Rare',
        url: 'https://imgur.com/toqw5H2.png',
        usable: false
    },
    {
        name: 'Shovel',
        description: 'Allows you to dig',
        sellPrice: 100,
        buyPrice: 25000,
        tradeValue: 2000,
        emoji: '<:Shovel:1005438385881620501>',
        id: 'shovel',
        type: 'Tool',
        rarity: 'Common',
        url: 'https://imgur.com/kyYulbe.png',
        usable: false
    },
    {
        name: 'Dev Coin',
        description: 'A coin from the devs. Why not use it?',
        sellPrice: 1,
        buyPrice: 0,
        tradeValue: 1000000,
        emoji: '<:DeveloperCoin:1005438384765947904>',
        id: 'dev coin',
        type: 'Collectable',
        rarity: 'Rare',
        url: 'https://imgur.com/VT0PNjk.png',
        usable: true
    },
    {
        name: 'Cheque',
        description: 'A handy little cheque that will give you an extra bit of bank space',
        sellPrice: 0,
        buyPrice: 50000,
        tradeValue: 20000,
        emoji: '<:Cheque:1005448240663117854>',
        id: 'cheque',
        type: 'Power-Up',
        rarity: 'Common',
        url: 'https://imgur.com/ziHIdlX.png',
        usable: true
    },
    {
        name: 'Scout',
        description: 'A simple image of scout', //Found while hunting
        sellPrice: 3000000,
        buyPrice: 0,
        tradeValue: 2500000,
        emoji: '<:Scout:1005521226887864480>',
        id: 'scout',
        type: 'Power-Up',
        rarity: 'Rare',
        url: 'https://imgur.com/AmdBWTP.png',
        usable: true
    },
    {
        name: 'Rifle',
        description: 'Get one of these and go out to hunt',
        sellPrice: 10000,
        buyPrice: 20000,
        tradeValue: 200,
        emoji: '',
        id: 'rifle',
        type: 'Tool',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Rocket Fuel',
        description: 'Load up your rocket and fly off to a new planet',
        sellPrice: 0,
        buyPrice: 0,
        tradeValue: 10000,
        emoji: '',
        id: 'rocket fuel',
        type: 'Craftable',
        rarity: 'Uncommon',
        url: '',
        usable: false
    },
    {
        name: 'Rocket',
        description: 'Needed to get to new planets',
        sellPrice: 0,
        buyPrice: 0,
        tradeValue: 100000,
        emoji: '',
        id: 'rocket',
        type: 'Tool',
        rarity: 'Rare',
        url: '',
        usable: false //Need to change to true when added planets
    },
    {
        name: 'Super Computer',
        description: 'The brains for your rocket',
        sellPrice: 0,
        buyPrice: 0,
        tradeValue: 100000,
        emoji: '',
        id: 'super computer',
        type: 'Craftable',
        rarity: 'Rare',
        url: '',
        usable: false
    },
    {
        name: 'Space Goo',
        description: 'A strange, sticky substance. It smells. Found from launching a rocket',
        sellPrice: 10000,
        buyPrice: 0,
        tradeValue: 5000,
        emoji: '',
        id: 'space goo',
        type: 'Sellable',
        rarity: 'Uncommon',
        url: '',
        usable: false
    },
    {
        name: 'Plasma',
        description: 'Used to make weapons',
        sellPrice: 0,
        buyPrice: 0,
        tradeValue: 40000,
        emoji: '',
        id: 'plasma',
        type: 'Craftable',
        rarity: 'Rare',
        url: '',
        usable: false
    },
    {
        name: 'Air',
        description: 'How the...',
        sellPrice: 100,
        buyPrice: 0,
        tradeValue: 1000,
        emoji: '',
        id: 'air',
        type: 'Craftable',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Metal',
        description: 'Used to craft a rocket',
        sellPrice: 1000,
        buyPrice: 10000,
        tradeValue: 500,
        emoji: '',
        id: 'metal',
        type: 'Craftable',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Wood',
        description: 'A useful material that can be crafted into many things',
        sellPrice: 500,
        buyPrice: 5000,
        tradeValue: 250,
        emoji: '',
        id: 'wood',
        type: 'Craftable',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Plastic',
        description: 'An item found from fishing',
        sellPrice: 100,
        buyPrice: 0,
        tradeValue: 10,
        emoji: '',
        id: 'plastic',
        type: 'Craftable',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Tape',
        description: 'Found from digging, used to tape things together', //Make it so you can find while digging
        sellPrice: 200,
        buyPrice: 0,
        tradeValue: 100,
        emoji: '<:DuctTape:1006293231476166737>',
        id: 'tape',
        type: 'Craftable',
        rarity: 'Uncommon',
        url: 'https://imgur.com/ivNgi2i.png',
        usable: false
    },
    {
        name: 'Glue',
        description: 'Used to stick stuff to other stuff. Found in the ground',//Put in dig loot table
        sellPrice: 200,
        buyPrice: 0,
        tradeValue: 100,
        emoji: '<:Glue:1006637919873806416>',
        id: 'glue',
        type: 'Craftable',
        rarity: 'Uncommon',
        url: 'https://imgur.com/cCrzLe8.png',
        usable: false
    },
    {
        name: 'String',
        description: 'Used to craft a space suit',
        sellPrice: 100,
        buyPrice: 0,
        tradeValue: 10,
        emoji: '',
        id: 'string',
        type: 'Craftable',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Control Unit',
        description: 'Nessacery for making sure your rocket stays on course',
        sellPrice: 0,
        buyPrice: 0,
        tradeValue: 10000,
        emoji: '',
        id: 'control unit',
        type: 'Tool',
        rarity: 'Rare',
        url: '',
        usable: false
    },
    {
        name: 'Space Suit',
        description: 'Required to go onto other planets',
        sellPrice: 0,
        buyPrice: 0,
        tradeValue: 1000,
        emoji: '',
        id: 'space suit',
        type: 'Collectable',
        rarity: 'Uncommon',
        url: '',
        usable: false
    },
    {
        name: 'Axe',
        description: 'Wanna cut down a tree? You need one of these',
        sellPrice: 5000,
        buyPrice: 10000,
        tradeValue: 2000,
        emoji: '',
        id: 'axe',
        type: 'Tool',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Pickaxe',
        description: 'To go mining for minerals this could be helpful',
        sellPrice: 5000,
        buyPrice: 15000,
        tradeValue: 2500,
        emoji: '',
        id: 'pickaxe',
        type: 'Tool',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Pet Food',
        description: 'Required to keep your pet healthly',
        sellPrice: 0,
        buyPrice: 1000,
        tradeValue: 100,
        emoji: '',
        id: 'pet food',
        type: 'Collectable',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Ammo',
        description: 'Needed to keep your rifle loaded',
        sellPrice: 0,
        buyPrice: 100,
        tradeValue: 0,
        emoji: '',
        id: 'ammo',
        type: 'Tool',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Camera',
        description: 'Found while fishing. Doesn\'t work so might aswell sell it',
        sellPrice: 400,
        buyPrice: 0,
        tradeValue: 10,
        emoji: '',
        id: 'camera',
        type: 'Sellable',
        rarity: 'Uncommon',
        url: '',
        usable: false
    },
    {
        name: 'Rubbish',
        description: 'A bag of smelly rubbish',
        sellPrice: 200,
        buyPrice: 0,
        tradeValue: 100,
        emoji: '',
        id: 'rubbish',
        type: 'Sellable',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Squid',
        description: 'Tasty food + Hungry customers = Money',
        sellPrice: 100,
        buyPrice: 0,
        tradeValue: 10,
        emoji: '',
        id: 'squid',
        type: 'Sellable',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Fish',
        description: 'Fish and chips.',
        sellPrice: 100,
        buyPrice: 0,
        tradeValue: 10,
        emoji: '<:Fish:1006637918095413339>',
        id: 'fish',
        type: 'Sellable',
        rarity: 'Common',
        url: 'https://imgur.com/v3h1AZU.png',
        usable: false
    },
    {
        name: 'Duck',
        description: 'Why do so many people want a pet duck?',
        sellPrice: 100,
        buyPrice: 0,
        tradeValue: 10,
        emoji: '',
        id: 'duck',
        type: 'Sellable',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Snake',
        description: 'A bigger worm',
        sellPrice: 100,
        buyPrice: 0,
        tradeValue: 10,
        emoji: '',
        id: 'snake',
        type: 'Sellable',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Alien',
        description: 'Probably hopped onto your rocket while going through space. Why does it sell?',
        sellPrice: 1000,
        buyPrice: 0,
        tradeValue: 10,
        emoji: '',
        id: 'alien',
        type: 'Sellable',
        rarity: 'Uncommon',
        url: '',
        usable: false
    },
    {
        name: 'Fishing Rod',
        description: 'Used to go fishing in the river. Only helpfull on planets with water',
        sellPrice: 4000,
        buyPrice: 10000,
        tradeValue: 3000,
        emoji: '',
        id: 'rod',
        type: 'Tool',
        rarity: 'Common',
        url: '',
        usable: false
    },
    {
        name: 'Pet Collar',
        description: 'Lets you give your pet a name',
        sellPrice: 750000,
        buyPrice: 1000000,
        tradeValue: 500000,
        emoji: '',
        id: 'pet collar',
        type: 'Collectable',
        rarity: 'Rare',
        url: '',
        usable: false
    },
    {
        name: 'Meteor',
        description: 'Found while traveling through space',
        sellPrice: 10000,
        buyPrice: 0,
        tradeValue: 5000,
        emoji: '',
        id: 'meteor',
        type: 'Sellable',
        rarity: 'Uncommon',
        url: '',
        usable: false
    },
    {
        name: 'Berries',
        description: 'You might get a good buff.... Or a bad one',
        sellPrice: 12000,
        buyPrice: 40000,
        tradeValue: 6000,
        emoji: '<:Berries:1006621693009215559>',
        id: 'berries',
        type: 'Collectable',
        rarity: 'Uncommon',
        url: 'https://imgur.com/IifsgUx.png',
        usable: true
    },
    {
        name: 'Minerals',
        description: 'Can be sold for a hefty sum of cash',
        sellPrice: 6000,
        buyPrice: 0,
        tradeValue: 3000,
        emoji: '<:Minerals:1006628025552609450>',
        id: 'minerals',
        type: 'Sellable',
        rarity: 'Uncommon',
        url: 'https://imgur.com/7gROPNF.png',
        usable: false
    },{
        name: 'Rocks',
        description: 'Found while mining',
        sellPrice: 100,
        buyPrice: 0,
        tradeValue: 10,
        emoji: '<:Rocks:1006628026739589270>',
        id: 'rocks',
        type: 'Sellable',
        rarity: 'Common',
        url: 'https://imgur.com/yOxqj2t.png',
        usable: false
    },
]