module.exports = [
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    },
    {
        name: '',
        subtitle: '',
        description: '',
        health: 0,
        damagePerHitMax: 0,
        damagePerHitMin: 0,
        defence: 0,
        difficulty: '',
        emoji: '',
        url: ''
    }
]